export const FETCH_FRIENDS_LIST = "FETCH_FRIENDS_LIST";
export const ADD_TO_FRIENDS = "ADD_TO_FRIENDS";
export const ACCEPT_TO_FRIENDS = "ACCEPT_TO_FRIENDS";
export const FETCH_FRIENDS_INVITATIONS_LIST = "FETCH_FRIENDS_INVITATIONS_LIST";
