export const GET_FEED_BY_USER = "GET_FEED_BY_USER";
export const BECOME_MEMBER_CODE = "BECOME_MEMBER_CODE";
export const CONFIRM_MEMBER_CODE = "CONFIRM_MEMBER_CODE";
export const CHECK_PROFILE_INVOICE = "CHECK_PROFILE_INVOICE";
