export const API_ENDPOINTS = {
	auth: {
		getTranslations: "/api/public/dictionaries/translations",
		initForgotPassword: "/api/public/user/forgot-password/initiate",
		continueForgotPassword: "/api/secure-code/forgot-password/confirm",
		finishForgotPassword: "/api/public/user/forgot-password/finish",
		sendCode: "/api/secure-code/registration/send",
		confirmCode: "/api/secure-code/registration/confirm",
		fetchProfile: "/api/private/user/profile",
		updateProfile: "/api/private/user/profile/update",
		user: {
			create: "/api/public/user/create-account",
			checkEmail: "/api/public/user/check-email",
			login: "/api/public/user/login",
		},
		social: {
			create: "/api/public/user/social/create-account",
			login: "/api/public/user/social/login",
		},
	},
	feed: {
		common: "/api/public/feed/common",
		findByUser: "/api/public/feed/user",
		setLike: "/api/private/feed/like",
		createPost: "/api/private/post/create",
		getPost: "/api/public/post/get",
	},
	groups: {
		find: "/api/public/groups/find",
		getTop: "/api/public/groups/top-groups",
		getImage: "/api/public/groups/images",
		getFeed: "/api/public/feed/group",
		getWallet: "/api/private/wallet/group/list",
		getWalletTransactions: "/api/private/wallet/group/transactions",
		findById: "/api/public/groups/find-by-id",
		follow: "/api/private/groups/follow",
		unfollow: "/api/private/groups/unfollow",
		getCountries: "/api/public/dictionaries/countries",
		create: "/api/private/groups/create",
		update: "/api/private/groups/update",
		findMembers: "/api/public/groups/members/find",
		changeApplicantRole: "/api/private/groups/change-role",
	},
	messenger: {
		getChatslist: "/api/private/messenger/chat/list",
		createChat: "/api/private/messenger/chat/create",
		removeChat: "/api/private/messenger/chat/remove",
		getMessagesList: "/api/private/messenger/message/list",
		sendMessage: "/api/private/messenger/message/create",
		sendAttachment: "/api/private/messenger/attachment/create",
		readAll: "/api/private/messenger/message/read-all",
	},
	friends: {
		getList: "/api/public/friend/find",
		getInvitations: "/api/private/friend/invitations/find",
		sendRequest: "/api/private/friend/send",
		declineRequest: "/api/private/friend/decline",
		acceptRequest: "/api/private/friend/accept",
	},
	becomeMember: {
		sendCode: "/api/secure-code/become-member/send",
		confirmCode: "/api/secure-code/become-member/confirm",
		checkPayment: "/api/private/wayforpay/become-member/invoice",
	},
	users: {
		find: "/api/public/user/find",
		findById: "/api/public/user/profile/",
	},
	articles: {
		list: "/api/public/article/list",
		getById: "/api/public/article/get",
		create: "/api/private/article/create",
		update: "/api/private/article/update",
	},
	events: {
		list: "/api/public/event/list",
		getById: "/api/public/event/get",
		create: "/api/private/event/create",
	},
	solutions: {
		list: "/api/public/voting/list",
		findById: "/api/public/voting/get/",
		vote: "/api/private/voting/vote",
		createOne: "/api/private/voting/create",
		update: "/api/private/voting/update",
		updateSolution: "/api/private/voting/solution/create",
	},
	comments: {
		create: "/api/private/comment/create",
		list: "/api/public/comment/list",
	},
	proposals: {
		list: "/api/public/proposal/find",
		vote: "/api/private/proposal/vote",
	},
};
